### ISSUE TITLE
html code visible in frontpage

### ISSUE THREAD

**Issue by olafito18** [vegastrike/vegastrike.github.io#8]
At the bottom of these pages there is html code

https://www.vega-strike.org/blog/2020/05/04/release-roadmap/
https://www.vega-strike.org/blog/2020/04/30/vs-website-is-up/

**Comment by nabaco** [comment]
Thank you for noticing and reporting. I will have a look at this tomorrow. It might be due to the recent security update.

**Comment by nabaco** [comment]
I have found the root cause. In https://www.github.com/vegastrike/vegastrike.github.io/tree/master/_includes%2Fshare.html in the linkedin button I'm including the post's description (excerpt), which I made longer using the `<!-- more --> ` tag in the posts themselves. That's why in some posts the button shows correctly and in some not.
I'll have to see how I can either encode the description in the URL or remove it altogether.
Well deal with that tomorrow
